name: Issue Check

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  validate-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Handle unlabeled issues
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const labels = issue.labels;

            if (!labels || labels.length === 0) {
              const issueNumber = issue.number;
              const issueCreator = issue.user.login;

              const warningComment = `🚫 This issue has been closed because it was created without any labels. Please reopen and add at least one label. @${issueCreator}`;

              // Post comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: warningComment
              });

              // Close issue
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                state: "closed"
              });

              // Optionally fail the job (if you want)
              core.setFailed("Issue closed due to missing labels.");
            }
