name: Issue Check

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read
<<<<<<< HEAD
  metadata: read
=======
>>>>>>> develop

jobs:
  validate-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check for labels
        if: ${{ github.event.issue.labels == '' }}
        run: |
          echo "❌ No labels found. Please add at least one label."
          exit 1

      - name: Check for assignee
        if: ${{ github.event.issue.assignees == '' }}
        run: |
          COMMENT_BODY="⚠️ This issue has no assignee. Please assign it to a user. @${{ github.event.issue.user.login }}"
          gh issue comment ${{ github.event.issue.number }} --body "$COMMENT_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

