name: Welcome Issue Comment

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: actions/github-script@v7
        with:
          script: |
            const issueCreator = context.payload.issue.user.login;
            const issueNumber = context.payload.issue.number;
            const commentBody = `Hi @${issueCreator}, thanks for opening this issue! We'll take a look shortly.`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: commentBody
            });
