name: Issue Check

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  validate-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check for labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.issue.labels;
            if (!labels || labels.length === 0) {
              core.setFailed("❌ No labels found. Please add at least one label.");
            }

      - name: Check for assignee and comment if missing
        uses: actions/github-script@v7
        with:
          script: |
            const assignees = context.payload.issue.assignees;
            if (!assignees || assignees.length === 0) {
              const issueNumber = context.payload.issue.number;
              const issueCreator = context.payload.issue.user.login;

              const body = `⚠️ This issue has no assignee. Please assign it to someone. @${issueCreator}`;
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: body
              });
            }
